/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error": "#fff7f7",
        "surface-dim": "#dcd9df",
        "on-secondary-fixed-variant": "#5f586e",
        "on-secondary-fixed": "#423c50",
        "primary-dim": "#5b4497",
        "surface-variant": "#e5e1e7",
        "secondary": "#625c71",
        "on-secondary": "#fdf7ff",
        "on-primary-container": "#381e72",
        "surface-container-low": "#f6f2f6",
        "tertiary-fixed-dim": "#e5b2d5",
        "inverse-primary": "#bba2fd",
        "tertiary": "#7b5270",
        "surface-container": "#f0edf1",
        "surface-bright": "#fcf8fb",
        "on-surface-variant": "#605e63",
        "surface-tint": "#6750a5",
        "on-surface": "#323236",
        "tertiary-fixed": "#f4bfe3",
        "surface": "#fcf8fb",
        "secondary-dim": "#565065",
        "on-primary-fixed-variant": "#41297c",
        "on-error-container": "#6e0523",
        "surface-container-high": "#eae7ec",
        "primary-fixed": "#bba2fd",
        "on-background": "#323236",
        "outline": "#7c7a7f",
        "on-primary-fixed": "#1e0053",
        "on-secondary-container": "#554f63",
        "on-tertiary": "#fff7f9",
        "tertiary-container": "#f4bfe3",
        "error-container": "#f97386",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#bba2fd",
        "inverse-on-surface": "#9e9c9f",
        "inverse-surface": "#0e0e10",
        "tertiary-dim": "#6e4664",
        "outline-variant": "#b3b1b7",
        "secondary-container": "#e8def8",
        "on-tertiary-container": "#5f3956",
        "on-tertiary-fixed": "#4a2642",
        "on-primary": "#fdf7ff",
        "secondary-fixed": "#e8def8",
        "secondary-fixed-dim": "#dad0ea",
        "primary": "#6750a5",
        "surface-container-highest": "#e5e1e7",
        "on-tertiary-fixed-variant": "#694260",
        "error": "#a8364b",
        "primary-fixed-dim": "#ad95ef",
        "background": "#fcf8fb",
        "error-dim": "#6b0221"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
};